### ISSUE TITLE
Nightly failed for incorrect URL (?)

### ISSUE THREAD

**Issue by tripleee** [tripleee/sloshy#14]
The last couple of nights, the run has failed after several hours with a traceback ending with

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chat.stackexchange.com/chats/111121/messages/new
92
Error: The operation was canceled.
```

See https://github.com/tripleee/sloshy/actions/runs/1129571072 and the one from the previous night.

**Comment by tripleee** [comment]
Turns out that the room where this was happening was forcibly frozen by a mod.

https://chat.stackexchange.com/transcript/111121

**Comment by tripleee** [comment]
Left a ping in chat to alert the stakeholders: https://chat.stackexchange.com/transcript/message/58884002#58884002

**Comment by tripleee** [comment]
Still want to prevent this crash if it should happen again. It was fortunate that the problematic room was the last one in the YAML file, so it didn't prevent Sloshy from doing its job over the last few days.

**Comment by tripleee** [comment]
The actual error is pretty deep inside the ChatExchange library. Fixing will probably require an upstream patch.

Just to keep this self-contained, here issthe full traceback from Nightly \#67.

```
Exception in thread message_sender:
72
Traceback (most recent call last):
73
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
74
    self.run()
75
  File "/usr/lib/python3.8/threading.py", line 870, in run
76
    self._target(*self._args, **self._kwargs)
77
  File "/home/runner/.local/lib/python3.8/site-packages/chatexchange/client.py", line 183, in _worker
78
    self._do_action_despite_throttling(next_action)
79
  File "/home/runner/.local/lib/python3.8/site-packages/chatexchange/client.py", line 221, in _do_action_despite_throttling
80
    response = self._br.send_message(room_id, text)
81
  File "/home/runner/.local/lib/python3.8/site-packages/chatexchange/browser.py", line 299, in send_message
82
    return self.post_fkeyed(
83
  File "/home/runner/.local/lib/python3.8/site-packages/chatexchange/browser.py", line 133, in post_fkeyed
84
    return self.post(url, data, headers)
85
  File "/home/runner/.local/lib/python3.8/site-packages/chatexchange/browser.py", line 113, in post
86
    return self._request('post', url, data, headers, with_chat_root)
87
  File "/home/runner/.local/lib/python3.8/site-packages/chatexchange/browser.py", line 102, in _request
88
    response.raise_for_status()
89
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
90
    raise HTTPError(http_error_msg, response=self)
91
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chat.stackexchange.com/chats/111121/messages/new
92
Error: The operation was canceled.
```

**Comment by ndattani** [comment]
Hi @tripleee this was a Chemistry.SE room and a mod over there seems to have unilaterally frozen the room (MMSE and Chemistry.SE compete for the same audiences after all). We have a similar room on Physics.SE (https://chat.stackexchange.com/rooms/111122/questions-about-the-modeling-of-matter) which has not had such an unfortunate circumstance of getting frozen (in fact the Physics.SE mods have incorporated MMSE into the ticker feeds of their _main_ chat room too). I can ask the Physics.SE mods in advance if we can keep that room unfrozen there.

Apart from the rooms mentioned above (one already frozen, and one for which I'll ask the mods if it can be kept unfrozen), I don't see any issue with rooms on the Sloshy list freezing anymore, because they're Matter Modeling rooms, and @TyBalduf has already approved having these rooms kept open (if a mod from a different site freezes them for some reason, Ty would likely just unfreeze it again, since it's an MMSE room and a mod from a different site is not an MMSE mod).

**Comment by tripleee** [comment]
Thanks for the background. I 'd appreciate if you could get explicit approval for the Physics room still, thanks. Can I open a separate ticket about that and assign it to you @ndattani?

**Comment by tripleee** [comment]
The actual acute error was in the scraper logic, it just manifested with a really deep chat traceback in production. Calling this fixed now, as the latest commit adds robustness for several failure cases.

**Comment by tripleee** [comment]
The robustness fixes still don't completely address the Chemistry room in particular; Sloshy is left trying to deliver the chat message for hours before finally giving up with a timeout. I'm thinking the simplest fix for that is to run with `--test-rooms` in the nightly job before the main job.

**Comment by tripleee** [comment]
(Previous comment implemented now; https://github.com/tripleee/sloshy/commit/0a68f24d867e67bb46df8b20f3dc427c23e23b1c)

**Comment by tripleee** [comment]
https://github.com/tripleee/sloshy/commit/6e884ae174830acbefec5a7715cc6402f447aeea adds an explicit check to raise an exception if a room's info page indicates that it is frozen or deleted.
