### ISSUE TITLE
Nightly runs failed

### ISSUE THREAD

**Issue by tripleee** [tripleee/sloshy#59]
[Several](https://github.com/tripleee/sloshy/actions/runs/5958535950) [recent](https://github.com/tripleee/sloshy/actions/runs/5970963490) [nightly](https://github.com/tripleee/sloshy/actions/runs/5982143550) [runs](https://github.com/tripleee/sloshy/actions/runs/5988266779) failed. The transcript in Sloshy's room seems to indicate that the run finished successfully, but obviously something did not work as expected.

```
Exception in thread ChatExchange: message_sender for chat.stackexchange.com:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/client.py", line 229, in _worker
    self._do_action_despite_throttling(next_action)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/client.py", line 265, in _do_action_despite_throttling
    response = self._br.send_message(room_id, text)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 318, in send_message
    return self.post_fkeyed(
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 136, in post_fkeyed
    return self.post(url, data, headers)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 116, in post
    return self._request('post', url, data, headers, with_chat_root)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 105, in _request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chat.stackexchange.com/chats/138453/messages/new
```

138453 is Chemistry: Downvoting

**Comment by tripleee** [comment]
The room was manually frozen a few days ago. https://chat.stackexchange.com/transcript/message/64235940#64235940

I left a question in the site's main room asking why; but in the meantime, I'll remove this room. https://chat.stackexchange.com/transcript/message/64274083#64274083
