### ISSUE TITLE
Nightly failed; CAPTCHA problem?

### ISSUE THREAD

**Issue by tripleee** [tripleee/sloshy#65]
https://github.com/tripleee/sloshy/actions/runs/6269189951/job/17025251861 failed, possibly because of the [recent migration to Cloudflare.](https://meta.stackexchange.com/questions/393116/every-site-requesting-verification-that-im-human)

```none
Traceback (most recent call last):
  File "/home/runner/work/sloshy/sloshy/./run.py", line 19, in <module>
    sloshy.test_rooms()
  File "/home/runner/work/sloshy/sloshy/sloshy.py", line 395, in test_rooms
    room.send_message("")  # just join, don't send anything
  File "/home/runner/work/sloshy/sloshy/sloshy.py", line 168, in send_message
    chat = self.clients.get_client_for_server(self.server)
  File "/home/runner/work/sloshy/sloshy/sloshy.py", line 104, in get_client_for_server
    client.login(self.email, self.password)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/client.py", line 169, in login
    cookies = self._br.login_site(self.host, email, password)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 151, in login_site
    self._se_openid_login_with_fkey(
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 198, in _se_openid_login_with_fkey
    response = self.post(post_url, data, with_chat_root=False)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 116, in post
    return self._request('post', url, data, headers, with_chat_root)
  File "/home/runner/.local/lib/python3.10/site-packages/chatexchange/browser.py", line 105, in _request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://meta.stackexchange.com/
Error: Process completed with exit code 1.
```

There was another login error last week, but that had the traditional traceback and I disregarded it at the time as spurious; I'm still thinking it was, but including here for completeness.

https://github.com/tripleee/sloshy/actions/runs/6192982628/job/16813820126

**Comment by tripleee** [comment]
[Left a comment on Meta.](https://meta.stackexchange.com/questions/393116/every-site-requesting-verification-that-im-human#comment1315101_393125)

**Comment by tripleee** [comment]
Seems to have been fixed by SE.
