### ISSUE TITLE
Sloshy says he announced his presence, but he didn't

### ISSUE THREAD

**Issue by tripleee** [tripleee/sloshy#85]
https://chat.stackoverflow.com/transcript/message/57225157#57225157 will have failed because of write access issues and the subsequent ones were probably blocked because of that. Something wrong in how the queue is (not) drained?

**Comment by tripleee** [comment]
https://app.circleci.com/pipelines/github/tripleee/sloshy/74/workflows/eb2bc2bb-ed63-4efd-9855-2fbc9cf45827/jobs/70 transcript:
```
python sloshy.py room-test.yaml \
   --announce "Sloshy is here! (See profile for details)" \
   --location_extra="CircleCI"
INFO:chatexchange.client.Client:Logged in.
INFO:chatexchange.client.Client:Worker thread reporting for duty.
INFO:chatexchange.rooms.Room:Queued message '[Sloshy](https://github.com/tripleee/sloshy) startup: Sloshy is here! (See profile for details) on d4b99849b8f7 (CircleCI)' for room_id #233626.
INFO:chatexchange.client.Client:Now serving customer 1, ('send', 233626, '[Sloshy](https://github.com/tripleee/sloshy) startup: Sloshy is here! (See profile for details) on d4b99849b8f7 (CircleCI)')
INFO:chatexchange.rooms.Room:Queue length: 0.
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:113019
INFO:root:Found: https://chat.stackexchange.com/transcript/113019?m=65413315#65413315
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:112358
INFO:root:Found: https://chat.stackexchange.com/transcript/112358?m=65353686#65353686
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:109805
INFO:root:Found: https://chat.stackexchange.com/transcript/109805?m=65358177#65358177
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:120383
INFO:root:Found: https://chat.stackexchange.com/transcript/120383?m=65358178#65358178
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:112878
INFO:root:Found: https://chat.stackexchange.com/transcript/112878?m=65358179#65358179
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:117642
INFO:root:Found: https://chat.stackexchange.com/transcript/117642?m=65365102#65365102
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:109983
INFO:root:Found: https://chat.stackexchange.com/transcript/109983?m=65372071#65372071
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:117114
INFO:root:Found: https://chat.stackexchange.com/transcript/117114?m=65372073#65372073
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:119831
INFO:root:Found: https://chat.stackexchange.com/transcript/119831?m=65372074#65372074
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:113915
INFO:root:Found: https://chat.stackexchange.com/transcript/113915?m=65372075#65372075
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:110569
INFO:root:Found: https://chat.stackexchange.com/transcript/110569?m=65372076#65372076
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:111469
INFO:root:Found: https://chat.stackexchange.com/transcript/111469?m=65372077#65372077
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:117652
INFO:root:Found: https://chat.stackexchange.com/transcript/117652?m=65372078#65372078
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:110288
INFO:root:Found: https://chat.stackexchange.com/transcript/110288?m=65372079#65372079
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:112274
INFO:root:Found: https://chat.stackexchange.com/transcript/112274?m=65372080#65372080
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:108277
INFO:root:Found: https://chat.stackexchange.com/transcript/108277?m=65372081#65372081
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:109935
INFO:root:Found: https://chat.stackexchange.com/transcript/109935?m=65307957#65307957
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:109905
INFO:root:Found: https://chat.stackexchange.com/transcript/109905?m=65372082#65372082
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:110113
INFO:root:Found: https://chat.stackexchange.com/transcript/110113?m=65358200#65358200
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:110431
INFO:root:Found: https://chat.stackexchange.com/transcript/110431?m=65349826#65349826
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:109902
INFO:root:Found: https://chat.stackexchange.com/transcript/109902?m=65390662#65390662
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:107328
INFO:root:Found: https://chat.stackexchange.com/transcript/107328?m=65378704#65378704
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:142409
INFO:root:Found: https://chat.stackexchange.com/transcript/142409?m=65378705#65378705
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:136776
INFO:root:Found: https://chat.stackexchange.com/transcript/136776?m=65405802#65405802
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:107323
INFO:root:Found: https://chat.stackexchange.com/transcript/107323?m=65378706#65378706
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:109797
INFO:root:Found: https://chat.stackexchange.com/transcript/109797?m=65378707#65378707
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:111122
INFO:root:Found: https://chat.stackexchange.com/transcript/111122?m=65378709#65378709
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:92073
INFO:root:Found: https://chat.stackexchange.com/transcript/92073?m=65405805#65405805
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:7310
INFO:root:Found: https://chat.stackexchange.com/transcript/7310?m=65394827#65394827
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:140197
INFO:root:Found: https://chat.stackexchange.com/transcript/140197?m=65390678#65390678
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:1090
INFO:root:Found: https://chat.stackexchange.com/transcript/1090?m=65349869#65349869
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:94323
INFO:root:Found: https://chat.stackexchange.com/transcript/94323?m=65378723#65378723
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:84778
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 514718 in room chat.stackexchange.com:84778
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 514718 in room chat.stackexchange.com:84778
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 514718 in room chat.stackexchange.com:84778
INFO:root:Found: https://chat.stackexchange.com/transcript/84778?m=63808080#63808080
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:146039
INFO:root:Found: https://chat.stackexchange.com/transcript/146039?m=65277893#65277893
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:241
INFO:root:Found: https://chat.stackexchange.com/transcript/241?m=65390679#65390679
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:591
INFO:root:Found: https://chat.stackexchange.com/transcript/591?m=65079293#65079293
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:110136
INFO:root:Found: https://chat.stackexchange.com/transcript/110136?m=65419760#65419760
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:39466
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 514718 in room chat.stackexchange.com:39466
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 514718 in room chat.stackexchange.com:39466
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 514718 in room chat.stackexchange.com:39466
INFO:root:Sleeping between searches ...
INFO:root:Searching for heat by user 514718 in room chat.stackexchange.com:39466
INFO:root:Sleeping between searches ...
INFO:root:Searching for thawman by user 514718 in room chat.stackexchange.com:39466
INFO:root:Sleeping between searches ...
INFO:root:Sleeping between searches ...
INFO:chatexchange.client.Client:Logging in.
INFO:chatexchange.client.Client:Logged in.
INFO:chatexchange.client.Client:Worker thread reporting for duty.
INFO:chatexchange.rooms.Room:Queued message '[tag:unfreeze] Sloshy is here! (See profile for details)' for room_id #39466.
INFO:chatexchange.client.Client:Now serving customer 1, ('send', 39466, '[tag:unfreeze] Sloshy is here! (See profile for details)')
INFO:chatexchange.rooms.Room:Queue length: 0.
INFO:root:announced presence in https://chat.stackexchange.com/rooms/39466
INFO:chatexchange.rooms.Room:Queued message 'announced presence in https://chat.stackexchange.com/rooms/39466' for room_id #233626.
INFO:chatexchange.rooms.Room:Queue length: 1.
INFO:chatexchange.client.Client:Now serving customer 2, ('send', 233626, 'announced presence in https://chat.stackexchange.com/rooms/39466')
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:125050
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 514718 in room chat.stackexchange.com:125050
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 514718 in room chat.stackexchange.com:125050
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 514718 in room chat.stackexchange.com:125050
INFO:root:Sleeping between searches ...
INFO:root:Searching for heat by user 514718 in room chat.stackexchange.com:125050
INFO:root:Sleeping between searches ...
INFO:root:Searching for thawman by user 514718 in room chat.stackexchange.com:125050
INFO:root:Sleeping between searches ...
INFO:root:Sleeping between searches ...
INFO:chatexchange.rooms.Room:Queued message '[tag:unfreeze] Sloshy is here! (See profile for details)' for room_id #125050.
INFO:chatexchange.client.Client:Now serving customer 2, ('send', 125050, '[tag:unfreeze] Sloshy is here! (See profile for details)')
INFO:chatexchange.rooms.Room:Queue length: 0.
INFO:root:announced presence in https://chat.stackexchange.com/rooms/125050
INFO:chatexchange.rooms.Room:Queued message 'announced presence in https://chat.stackexchange.com/rooms/125050' for room_id #233626.
INFO:chatexchange.rooms.Room:Queue length: 1.
INFO:chatexchange.client.Client:Now serving customer 3, ('send', 233626, 'announced presence in https://chat.stackexchange.com/rooms/125050')
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:123853
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 514718 in room chat.stackexchange.com:123853
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 514718 in room chat.stackexchange.com:123853
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 514718 in room chat.stackexchange.com:123853
INFO:root:Sleeping between searches ...
INFO:root:Searching for heat by user 514718 in room chat.stackexchange.com:123853
INFO:root:Sleeping between searches ...
INFO:root:Searching for thawman by user 514718 in room chat.stackexchange.com:123853
INFO:root:Sleeping between searches ...
INFO:root:Sleeping between searches ...
INFO:chatexchange.rooms.Room:Queued message '[tag:unfreeze] Sloshy is here! (See profile for details)' for room_id #123853.
INFO:chatexchange.client.Client:Now serving customer 3, ('send', 123853, '[tag:unfreeze] Sloshy is here! (See profile for details)')
INFO:chatexchange.rooms.Room:Queue length: 0.
Exception in thread ChatExchange: message_sender for chat.stackexchange.com:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/chatexchange/client.py", line 229, in _worker
    self._do_action_despite_throttling(next_action)
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/chatexchange/client.py", line 265, in _do_action_despite_throttling
    response = self._br.send_message(room_id, text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/chatexchange/browser.py", line 318, in send_message
    return self.post_fkeyed(
           ^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/chatexchange/browser.py", line 136, in post_fkeyed
    return self.post(url, data, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/chatexchange/browser.py", line 116, in post
    return self._request('post', url, data, headers, with_chat_root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/chatexchange/browser.py", line 105, in _request
    response.raise_for_status()
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chat.stackexchange.com/chats/123853/messages/new
INFO:root:announced presence in https://chat.stackexchange.com/rooms/123853
INFO:chatexchange.rooms.Room:Queued message 'announced presence in https://chat.stackexchange.com/rooms/123853' for room_id #233626.
INFO:chatexchange.client.Client:Now serving customer 4, ('send', 233626, 'announced presence in https://chat.stackexchange.com/rooms/123853')
INFO:chatexchange.rooms.Room:Queue length: 0.
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:137507
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 514718 in room chat.stackexchange.com:137507
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 514718 in room chat.stackexchange.com:137507
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 514718 in room chat.stackexchange.com:137507
INFO:root:Sleeping between searches ...
INFO:root:Searching for heat by user 514718 in room chat.stackexchange.com:137507
INFO:root:Sleeping between searches ...
INFO:root:Searching for thawman by user 514718 in room chat.stackexchange.com:137507
INFO:root:Sleeping between searches ...
INFO:root:Sleeping between searches ...
INFO:chatexchange.rooms.Room:Queued message '[tag:unfreeze] Sloshy is here! (See profile for details)' for room_id #137507.
INFO:chatexchange.rooms.Room:Queue length: 1.
INFO:root:announced presence in https://chat.stackexchange.com/rooms/137507
INFO:chatexchange.rooms.Room:Queued message 'announced presence in https://chat.stackexchange.com/rooms/137507' for room_id #233626.
INFO:chatexchange.client.Client:Now serving customer 5, ('send', 233626, 'announced presence in https://chat.stackexchange.com/rooms/137507')
INFO:chatexchange.rooms.Room:Queue length: 0.
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:147285
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 514718 in room chat.stackexchange.com:147285
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 514718 in room chat.stackexchange.com:147285
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 514718 in room chat.stackexchange.com:147285
INFO:root:Sleeping between searches ...
INFO:root:Searching for heat by user 514718 in room chat.stackexchange.com:147285
INFO:root:Sleeping between searches ...
INFO:root:Searching for thawman by user 514718 in room chat.stackexchange.com:147285
INFO:root:Sleeping between searches ...
INFO:root:Sleeping between searches ...
INFO:chatexchange.rooms.Room:Queued message '[tag:unfreeze] Sloshy is here! (See profile for details)' for room_id #147285.
INFO:chatexchange.rooms.Room:Queue length: 2.
INFO:root:announced presence in https://chat.stackexchange.com/rooms/147285
INFO:chatexchange.rooms.Room:Queued message 'announced presence in https://chat.stackexchange.com/rooms/147285' for room_id #233626.
INFO:chatexchange.client.Client:Now serving customer 6, ('send', 233626, 'announced presence in https://chat.stackexchange.com/rooms/147285')
INFO:chatexchange.rooms.Room:Queue length: 0.
INFO:root:Searching for tagged/unfreeze by user 514718 in room chat.stackexchange.com:147825
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 514718 in room chat.stackexchange.com:147825
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 514718 in room chat.stackexchange.com:147825
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 514718 in room chat.stackexchange.com:147825
INFO:root:Sleeping between searches ...
INFO:root:Searching for heat by user 514718 in room chat.stackexchange.com:147825
INFO:root:Sleeping between searches ...
INFO:root:Searching for thawman by user 514718 in room chat.stackexchange.com:147825
INFO:root:Sleeping between searches ...
INFO:root:Sleeping between searches ...
INFO:chatexchange.rooms.Room:Queued message '[tag:unfreeze] Sloshy is here! (See profile for details)' for room_id #147825.
INFO:chatexchange.rooms.Room:Queue length: 3.
INFO:root:announced presence in https://chat.stackexchange.com/rooms/147825
INFO:chatexchange.rooms.Room:Queued message 'announced presence in https://chat.stackexchange.com/rooms/147825' for room_id #233626.
INFO:chatexchange.rooms.Room:Queue length: 1.
INFO:chatexchange.client.Client:Now serving customer 7, ('send', 233626, 'announced presence in https://chat.stackexchange.com/rooms/147825')
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:111347
INFO:root:Sleeping between searches ...
INFO:root:Searching for thaw by user 16115299 in room chat.stackoverflow.com:111347
INFO:root:Sleeping between searches ...
INFO:root:Searching for antifreeze by user 16115299 in room chat.stackoverflow.com:111347
INFO:root:Sleeping between searches ...
INFO:root:Searching for freeze by user 16115299 in room chat.stackoverflow.com:111347
INFO:root:Sleeping between searches ...
INFO:root:Searching for heat by user 16115299 in room chat.stackoverflow.com:111347
INFO:root:Sleeping between searches ...
INFO:root:Searching for thawman by user 16115299 in room chat.stackoverflow.com:111347
INFO:root:Found: https://chat.stackoverflow.com/transcript/111347?m=56409570#56409570
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:109494
INFO:root:Found: https://chat.stackoverflow.com/transcript/109494?m=57221179#57221179
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:228186
INFO:root:Found: https://chat.stackoverflow.com/transcript/228186?m=57193507#57193507
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:233626
INFO:root:Found: https://chat.stackoverflow.com/transcript/233626?m=57225144#57225144
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:193903
INFO:root:Found: https://chat.stackoverflow.com/transcript/193903?m=57191893#57191893
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:232981
INFO:root:Found: https://chat.stackoverflow.com/transcript/232981?m=57205135#57205135
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:217630
INFO:root:Found: https://chat.stackoverflow.com/transcript/217630?m=57152821#57152821
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:240030
INFO:root:Found: https://chat.stackoverflow.com/transcript/240030?m=57211666#57211666
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:244392
INFO:root:Found: https://chat.stackoverflow.com/transcript/244392?m=57211670#57211670
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:214345
INFO:root:Found: https://chat.stackoverflow.com/transcript/214345?m=57127035#57127035
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:190503
INFO:root:Found: https://chat.stackoverflow.com/transcript/190503?m=57218253#57218253
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:249491
INFO:root:Found: https://chat.stackoverflow.com/transcript/249491?m=57208812#57208812
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:253110
INFO:root:Found: https://chat.stackoverflow.com/transcript/253110?m=56519720#56519720
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:253305
INFO:root:Found: https://chat.stackoverflow.com/transcript/253305?m=56540357#56540357
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:253387
INFO:root:Found: https://chat.stackoverflow.com/transcript/253387?m=57131076#57131076
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:252171
INFO:root:Found: https://chat.stackoverflow.com/transcript/252171?m=56565444#56565444
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:71097
INFO:root:Found: https://chat.stackoverflow.com/transcript/71097?m=57166982#57166982
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:202427
INFO:root:Found: https://chat.stackoverflow.com/transcript/202427?m=57224408#57224408
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:98569
INFO:root:Found: https://chat.stackoverflow.com/transcript/98569?m=56667336#56667336
INFO:root:Sleeping between searches ...
INFO:root:Searching for tagged/unfreeze by user 16115299 in room chat.stackoverflow.com:208985
INFO:root:Found: https://chat.stackoverflow.com/transcript/208985?m=57034541#57034541
INFO:root:Sleeping between searches ...
Exception ignored in: <function Client.__del__ at 0x7f6d996c5120>
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.12.2/lib/python3.12/site-packages/chatexchange/client.py", line 213, in __del__
    assert False, "You forgot to log out."
AssertionError: You forgot to log out.
```

**Comment by tripleee** [comment]
I guess the thread which ran the client on the other server crashed with the first traceback, and then no longer responded. It's hard to see how this could be fixed, other than by refactoring ChatExchange to be async instead of threaded.
