### ISSUE TITLE
Nightly timed out after 1h

### ISSUE THREAD

**Issue by tripleee** [tripleee/sloshy#87]
https://app.circleci.com/pipelines/github/tripleee/sloshy/138/workflows/3fc44a90-0d62-4d23-bc26-e1bf833b534f/jobs/135 failed at https://chat.stackoverflow.com/transcript/message/57381231#57381231 after 18 rooms, apparently because it exceeded the 1h timeout deadline on CircleCI.

**Comment by tripleee** [comment]
There was a 429 error earlier in the failed transcript; maybe that's the root cause?
```
2024-05-24 03:30:34.794825 [Matter Modeling: Questions related to Matter Modeling, but posted in other places (e.g. other SE sites, or Reddit)](https://chat.stackexchange.com/transcript/110113/2024/5/17): latest activity 2024-05-17 14:13:00 (6 days, 13:05:03 hours ago)
Exception in thread ChatExchange: message_sender for chat.stackoverflow.com:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/site-packages/chatexchange/client.py", line 229, in _worker
    self._do_action_despite_throttling(next_action)
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/site-packages/chatexchange/client.py", line 265, in _do_action_despite_throttling
    response = self._br.send_message(room_id, text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/site-packages/chatexchange/browser.py", line 318, in send_message
    return self.post_fkeyed(
           ^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/site-packages/chatexchange/browser.py", line 136, in post_fkeyed
    return self.post(url, data, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/site-packages/chatexchange/browser.py", line 116, in post
    return self._request('post', url, data, headers, with_chat_root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/site-packages/chatexchange/browser.py", line 105, in _request
    response.raise_for_status()
  File "/home/circleci/.pyenv/versions/3.12.3/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://chat.stackoverflow.com/chats/111347/messages/new
2024-05-24 03:33:22.208002 [Matter Modeling: Ask a Moderator](https://chat.stackexchange.com/transcript/110431): latest activity 2024-05-20 03:31:00 (3 days, 23:47:03 hours ago)
2024-05-24 03:33:25.438350 [Matter Modeling: Announcements of user or site milestones achieved](https://chat.stackexchange.com/transcript/109902): latest activity 2024-05-14 03:31:00 (9 days, 23:47:03 hours ago)
```

**Comment by tripleee** [comment]
For now, rerunning the job manually worked.

**Comment by tripleee** [comment]
Happened again on Saturday ([nightly #145](https://app.circleci.com/pipelines/github/tripleee/sloshy/147/workflows/a067d0d1-2f18-49b2-9100-cae5ef8c3ba4/jobs/145); [chat link](https://chat.stackoverflow.com/transcript/message/57401687#57401687)) but Sunday's job worked normally again.

**Comment by tripleee** [comment]
Again again [nightly #147](https://app.circleci.com/pipelines/github/tripleee/sloshy/149/workflows/66458245-4b52-4b5a-93b8-86a0d20b26b8/jobs/147), though this seems to have been purely a chat glitch.

**Comment by tripleee** [comment]
Again again [nightly #165](https://app.circleci.com/pipelines/github/tripleee/sloshy/163/workflows/a9183946-5813-4e83-a38c-b3d1db66dd20/jobs/155)

**Comment by tripleee** [comment]
Still timing out with 429 errors, though the transcript logic should now be sounder. Do I need to increase the sleep between traversals? It works on my laptop, though.

**Comment by tripleee** [comment]
https://github.com/tripleee/sloshy/commit/b34429f739866a62240724410ab2a6f6dd6ff011 adds a proper 429 retry handler

**Comment by tripleee** [comment]
PR:s #98 and #99 (silly typo) add a sleep when there's an error.

**Comment by tripleee** [comment]
Switching back to Github Actions seems to trivially fix this. Will proceed to disable CircleCI again.

For the future, my best vague guess is that it might need a bigger machine. https://circleci.com/docs/configuration-reference/#resourceclass

**Comment by tripleee** [comment]
It's not entirely obvious how to enable CircleCI again. https://circleci.com/docs/stop-building-a-project-on-circleci/ says to go through the steps to create a new project.
